# Treinamento Brewery Bees - Dennis
name: TreinamentoBreweryBees

settings:
  MARKETING_VERSION: '1.0.0'
  CURRENT_PROJECT_VERSION: 1.0.0
  SWIFT_VERSION: 5.10
  CODE_SIGN_IDENTITY: 'iPhone Developer'
  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"
  ARCHS: $(ARCHS_STANDARD)

options:
  bundleIdPrefix: br.com.TreinamentoBreweryBees
  xcodeVersion: '15.3'
  deploymentTarget:
    iOS: '17.4'

include:
  - xcodegen/packages.yml
  - xcodegen/targets.yml
  - xcodegen/schemes.yml
